@hostname = https://localhost:7114

### 1. Создаем первого пользователя (Alice)
POST {{hostname}}/api/users
Content-Type: application/json

{
  "username": "Alice",
  "email": "alice@lightchat.local"
}

###

### 2. Создаем второго пользователя (Bob)
POST {{hostname}}/api/users
Content-Type: application/json

{
  "username": "Bob",
  "email": "bob@lightchat.local"
}

###

### 3. Создаем комнату (чат)
POST {{hostname}}/api/chats
Content-Type: application/json

{
  "name": "General Room"
}

###

### 4. Добавляем Alice в чат (Сюда нужно будет подставить GUID из ответов выше!)
POST {{hostname}}/api/chats/members
Content-Type: application/json

{
  "chatId": "d6ba9373-07cd-4f3d-ba76-8ce4d3f551f5",
  "userId": "b5261391-a51c-425f-9bc2-de4b2bb4a243"
}

###

### 5. Добавляем Bob в чат
POST {{hostname}}/api/chats/members
Content-Type: application/json

{
  "chatId": "d6ba9373-07cd-4f3d-ba76-8ce4d3f551f5",
  "userId": "f5d3bddb-29bf-489b-bff4-38abd722c5fa"
}